### ISSUE TITLE
add package:dash_analytics

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/tools#1]
@eliasyishak, we now have a general mono repo for Dart tooling packages. Feel free to open a PR adding dash_analytics here; you'll want to put it as a subdirectory of the `pkgs/` dir. You shouldn't need to include any files from your `.github` dir.

This repo doesn't have a CI set up yet, but I'll do that once we have 1 package here.

**Comment by eliasyishak** [comment]
Awesome! Thanks @devoncarew, should get a PR drafted by Monday, wrapping up some final tests

**Comment by eliasyishak** [comment]
I've opened a PR at https://github.com/dart-lang/tools/pull/2 for adding the package.

Will I also be getting write access to this repo? I've added myself in the CODEOWNER file and got a warning from github

**Comment by devoncarew** [comment]
We don't generally use the a github `CODEOWNER` file for dart-lang repos (and I'm not 100% sure of what the pros and cons are myself).

The best way for you to get commit access would be to join the `dart-team` github team; I'll send you instructions.
