### ISSUE TITLE
Add an implementation of `transitiveClosure`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/tools#104]
https://en.wikipedia.org/wiki/Floyd%E2%80%93Warshall_algorithm

This should let us deprecate the one in package:collection
https://www.dartdocs.org/documentation/collection/1.14.3/collection/transitiveClosure.html

**Comment by freemansoft** [comment]
Does [this commit](https://github.com/dart-lang/tools/commit/cef9625d5ad172e0c6a56d2d744560afe67e3ca2) on the dart-lang tools close this issue at least on the dart-lang tools side? 

It added transative_closure.dart to this project.

**Comment by natebosch** [comment]
@lrhn - any opinions on whether we should deprecate the copy of `transitiveClosure` with the more restrictive data model from `package:collection`?

**Comment by lrhn** [comment]
Seems reasonable to deprecate.
The alternative is to make the existing function use the new implementation, but I don't want to add a dependency to `package:collection`.
If so, we should do so soon, so we can remove in next major version.
