### ISSUE TITLE
[extension_discovery] `findExtensions` fails when there is a package in `package_config.json` with no `packageUri`

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/tools#146]
I discovered this using flutter gallery. I got an exception and had to add some further print statements to get to the bottom of it, but it turns out the issue was the `flutter_gen` package. In the `package_config.json` file, this package is listed as such:
```
{"name":"flutter_gen","rootUri":"flutter_gen","languageVersion":"2.12"}
```

This appears to be the only package without a `package_uri` key. Is the `flutter_gen` package special? Can we fail gracefully when something like this pops up? This does not affect whether we can find extensions for other packages.

**Comment by jonasfj** [comment]
> Is the `flutter_gen` package special?

Ah, this is a hack that something in Flutter adds when `flutter.generate: true` is set in `pubspec.yaml`.
It's caused all sorts of problems throughout the entire stack :see_no_evil: 



> Can we fail gracefully when something like this pops up?

We can hardcode in `flutter_gen` as an exception to always skip.

**Comment by sigurdm** [comment]
> It's caused all sorts of problems throughout the entire stack 🙈

Yeah, and as extra "fun", somebody has released a package called `flutter_gen` (https://pub.dev/packages/flutter_gen) on pub.dev.
