### ISSUE TITLE
crash reporting

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/tools#15]
Are there plans for the `dash_analytics` package to provide support for crash reporting?

**Comment by eliasyishak** [comment]
That should be okay to send crash reporting to the GA endpoint, we'll just need to add an event enum for crash reporting for each tool. However, this GA instance shouldn't be used for debugging those crashes by sending stacktraces, etc.

On the flutter tools side, with the previous reporting package, we would send an event indicating a crash has occured to GA but also send the details around the crash to crash.corp.google.com with detailed information about the crash

**Comment by bwilkerson** [comment]
> ... also send the details around the crash to crash.corp.google.com ...

That's what I was referring to. We used to use the `telemetry` package in the SDK repo for both analytics and crash reporting. The question is whether the `analytics` package will have support for that.

**Comment by eliasyishak** [comment]
Ah I see what you mean now. I would need to familiarize myself with the how google crash reporting endpoint works but we could add another feature that can handle crash reporting as well and sends to a separate endpoint. But at the moment, this package isn't capable of handling this

**Comment by eliasyishak** [comment]
Closing this issue for now, feel free to re-open this if more discussion is needed...  but at the moment, it doesn't seem that `package:unified_analytics` will be reporting crashes for dash related tooling
