### ISSUE TITLE
Explore options for automatically creating a table of events to the readme that have been added

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/tools#159]
It's hard to tell exactly what events have been added  to this package -- we can explore using GitHub actions or something to automatically generate a markdown table that clearly shows what's been added and when.

**Comment by eliasyishak** [comment]
Briefly looked into how we can do this today, seems like the `dart:mirrors` package could be useful for extracting a list of the named constructors for the `Event` class.. from there we could use this list to publish some kind of document into the github repo via github actions.

**Comment by leighajarett** [comment]
I've added this as an app script to this sheet, which runs each morning: and grabs the fields in the enums and event files on main. This way there's an easy way to view all the fields that have been added as a table.

https://docs.google.com/spreadsheets/d/12fUrmwmShlWYeBGl0_TEOt_FVTB1KTxru0mPOT1qFA8/edit#gid=76461167
