### ISSUE TITLE
Add host OS version and language as user properties

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/tools#188]
### Has this already been approved in the privacy design documentation?

- [X] This field is already covered in the PDD

### User property name

host_os_version, host_language

### User property values

This was covered in the previous google analytics using the device.operatingSystemVersion and device.language field respectively. The OS version was also covered in the sessionHostOsDetails custom dimension. 

Examples of the host_os_version are: Microsoft Windows [Version 10.0.22621.382],  macOS 11.2.3 20D91 darwin-arm, macOS 13.3 22E8252 darwin-arm64. Alternatively, we can just use the version itself and rely on the host user property for the operating system name. 

Examples of the host_language are 'ja-jp', 'en-in', 'zh-hans-cn', 'en-us', 'fr-fr'

**Comment by eliasyishak** [comment]
Closing as complete in the following PR:
- https://github.com/dart-lang/tools/pull/195
