### ISSUE TITLE
Create a user property for the user's IDE

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/tools#189]
### Has this already been approved in the privacy design documentation?

- [X] This field is already covered in the PDD

### User property name

ide

### User property values

This was previously tracked in the hits.appInfo.appInstallerId in the previous iteration of Google Analytics. 

Some of the unique values are ['Android-Studio', 'VSCode', '(not set)', 'IntelliJ-IDEA', 'WebStorm']

**Comment by bwilkerson** [comment]
Note that this data is similar to data collected in the `Event.serverSession` API. Specifically, that API collects the `clientId` and `clientVersion` reported by the client (usually an IDE plugin) to the Dart language server. We would need to double check, but I believe that all of the `ide` values listed above, and more, are being reported by the existing API. The existing API is also capturing the version of the plugin being used.

The one difference is that the `serverSession` event is only reported by the language server, so users of an IDE that doesn't include one of the plugins that uses the language server won't be reported. If we have users that are using DevTools but not the language server, then we won't have an IDE reported for them through the existing API.

If we believe that we need to capture both pieces of information I don't have a problem with it, but I wanted to make sure we were aware of the potential duplication.

**Comment by eliasyishak** [comment]
I think for the field @leighajarett pointed out, it is referring to what IDE is running the flutter tool. For example, running `flutter run` in the terminal within VS Code _or_ using the builtin run button in the UI would add information to each event about which IDE it ran from.

And on the other hand, if the user invokes `flutter run` from the host terminal, it would result in the IDE field being null which results in the `(not set)` value.

**Comment by eliasyishak** [comment]
Closing as complete in the following PR:
- https://github.com/dart-lang/tools/pull/195
