### ISSUE TITLE
Create a user property for commandHasTerminal

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/tools#197]
### Has this already been approved in the privacy design documentation?

- [X] This field is already covered in the PDD

### User property name

In the previous export, we had a boolean field called `commandHasTerminal` which helps us filter out "users" that we think are bots. 

### User property values

true / false

**Comment by christopherfujino** [comment]
user property sounds good to me. to verify my understanding, we're currently associating this field with every event, but moving it to a user property would instead associate it with the session?

**Comment by eliasyishak** [comment]
This was completed in:
- #204
