### ISSUE TITLE
Track enabled features 

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/tools#198]
### Has this already been approved in the privacy design documentation?

- [x] This field is already covered in the PDD

### Event name

In the previous google analytics for the Flutter tool, there was a field called `enabledFlutterFeatures` 

This has values like "enable-linux-desktop" and it seems to be specific to a feature (i.e. was that feature enabled on linux). However, I'm not entirely sure what that means or how it was calculated.

### Event data

TBD - perhaps there is a better way to handle this?

**Comment by leighajarett** [comment]
@christopherfujino do you have anymore information on this field? Any ideas for how we can better represent it?

**Comment by christopherfujino** [comment]
> @christopherfujino do you have anymore information on this field? Any ideas for how we can better represent it?

Sorry, I don't :) I'm not sure how it's represented currently, I just know that we have done one-off queries for experimental features to track opt in usage.

**Comment by eliasyishak** [comment]
We can probably add this as a field with the `Event.commandUsageValues`. Previously it seems like this value was being set at the session level and we don't have that hierarchical structure anymore.

But we do send  `Event.commandUsageValues` with every flutter command that is run so this may be our best approach

**Comment by eliasyishak** [comment]
Closing since #217 got merged in
