### ISSUE TITLE
Normalizing an existing file URI breaks extension discovery

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/tools#220]
When calling `findExtensions` the `packageConfig` uri that is passed in is normalized here:
https://github.com/dart-lang/tools/blob/main/pkgs/extension_discovery/lib/extension_discovery.dart#L150

`File.fromUri(packageConfig).absolute.uri;`

This causes issues when `packageConfig` is already a file URI.

Example: when the URI "file:///Users/kenzieschmoll/develop/gallery/.dart_tool/package_config.json" is passed, the code above transforms this URI to "file:///Users/kenzieschmoll/develop/dart-sdk/sdk/file:///Users/kenzieschmoll/develop/gallery/.dart_tool/package_config.json", which then causes an error to be thrown indicating the package config file cannot be found.

This is breaking DevTools extension support. @jonasfj

**Comment by kenzieschmoll** [comment]
In DevTools PR https://github.com/flutter/devtools/commit/89c7a4861fbd874c5af5c919a95a6e32af0fedcc, we started passing in File URIs to support windows users but this appears to have broken things for linux. CC @DanTup 

Can we make extension_discovery more robust so that it can handle file URIs too?

**Comment by kenzieschmoll** [comment]
The code for determining an absolute path seems odd that it doesn't take file uris into account: https://github.com/dart-lang/sdk/blob/66445534ea81db03a3c47831d0a830ff9c3f05f2/sdk/lib/io/file_system_entity.dart#L535-L544

**Comment by DanTup** [comment]
> Example: when the URI "file:///Users/kenzieschmoll/develop/gallery/.dart_tool/package_config.json" is passed, the code above transforms this URI to "file:///Users/kenzieschmoll/develop/dart-sdk/sdk/file:///Users/kenzieschmoll/develop/gallery/.dart_tool/package_config.json", which then causes an error to be thrown indicating the package config file cannot be found.

Do you have an exact code sample that reproduces this? I tried on macOS but couldn't reproduce. Given:

```dart
import 'dart:io';

void main() {
  final packageConfig = Uri.parse(
      'file:///Users/kenzieschmoll/develop/gallery/.dart_tool/package_config.json');
  print(File.fromUri(packageConfig).absolute.uri);
}
```

I see:

```
file:///Users/kenzieschmoll/develop/gallery/.dart_tool/package_config.json
```

From your comment is sounds like this is only a Linux issue, but I can't think of a reason why Linux and macOS wouldn't match.

> The code for determining an absolute path seems odd that it doesn't take file uris into account: https://github.com/dart-lang/sdk/blob/66445534ea81db03a3c47831d0a830ff9c3f05f2/sdk/lib/io/file_system_entity.dart#L535-L544

Isn't this class only dealing with paths, not URIs?

Hmm, I'm slightly suspicious about [this line here](https://github.com/dart-lang/tools/blob/56a30cea066bebbee9907eaa81df33ea41cd3806/pkgs/extension_discovery/lib/extension_discovery.dart#L138C7-L138C66):

```dart
(packageConfig.hasScheme && !packageConfig.isScheme('file')
```

Why is it allowing empty schemes? Is the broken path here getting a URI without a scheme? If so, I think we should remove that `hasScheme` check, always throw if it's not `isScheme('file')` and fix the source of the URI.

**Comment by kenzieschmoll** [comment]
To repro this, I am on flutter master and serving DevTools with `devtools_tool server --build-mode=debug`. Then running Flutter gallery and connecting to DevTools. For whatever reason `File.fromUri(packageConfig).absolute.uri` prefixes my file URI with `file:///Users/kenzieschmoll/develop/dart-sdk/sdk/`.

You are right that the file uri returned false for `isScheme('file')`. It seems strange that the `Uri.file` constructor does not automatically create a URI object with the 'file' scheme: https://github.com/dart-lang/sdk/blob/66445534ea81db03a3c47831d0a830ff9c3f05f2/sdk/lib/core/uri.dart#L1868

**Comment by kenzieschmoll** [comment]
I pushed up https://github.com/flutter/devtools/pull/6961 as a temporary fix. Although I still don't understand why `Uri.file` doesn't work for Mac but does for Windows. @DanTup can you confirm that using `Uri.file` indeed behaves as expected for windows?

Either way, there seems to be something fishy going on with `Uri.file` not constructing a URI where `uri.isScheme('file')` is true by default, as well as with the funky `file.absolute` prefixing with the current directory.

**Comment by DanTup** [comment]
> Although I still don't understand why Uri.file doesn't work for Mac but does for Windows. @DanTup can you confirm that using Uri.file indeed behaves as expected for windows?

Do you have a code sample you can run in isolation that triggers this? I did some testing on dartpad, but the only way I can get a Uri (using `Uri.file`) without the scheme is if it's relative (it's not clear to me if this is a bug, or if file: URIs don't support relative paths):

```dart
  print(Uri.parse('/foo/bar.dart'));        //    /foo/bar.dart
  print(Uri.parse('/foo/bar.dart').scheme); //    (blank)
  print(Uri.file('/foo/bar.dart'));         //    file:///foo/bar.dart
  print(Uri.file('/foo/bar.dart').scheme);  //    file
  print(Uri.file('foo/bar.dart'));          //    foo/bar.dart
  print(Uri.file('foo/bar.dart').scheme);   //    (blank)
```

**Comment by DanTup** [comment]
Ok, I reproduced this, and the real issue is that `Future<void> serveAvailableExtensions(String? rootPath)` is being called with a `rootPath` like `file:///Users/danny/Dev/Google/flutter_gallery` - which is a string URI and _not_ a "path".

If we do `Uri.file('file:///Users/danny/Dev/Google/flutter_gallery')` then we (understandably) get something broken, and using `Uri.parse()` is somewhat offsetting that.

I think the correct fix is to fix the call to `serveAvailableExtensions` to pass a path, not a string that is a file URI (and with that, you'll likely need to revert your workaround), or we change the signature to take `Uri rootUri` and ensure it's always a file URI.
