### ISSUE TITLE
☂️ Create a survey handler class to enable package to share surveys

### ISSUE THREAD

**Issue by eliasyishak** [dart-lang/tools#81]
This new class will enable the package to pull information for available surveys from a remote location and work with certain clients of this package (Language server) to share those surveys

fyi @jayoung-lee

Main feature branch:
- https://github.com/dart-lang/tools/pull/109

PR(s) tracking this functionality:
- [x] https://github.com/dart-lang/tools/pull/91
- [x] https://github.com/dart-lang/tools/pull/99
- [x] https://github.com/dart-lang/tools/pull/127
- [x] https://github.com/dart-lang/tools/pull/122
- [x] https://github.com/dart-lang/tools/pull/130
- [x] https://github.com/dart-lang/tools/pull/133
- [x] https://github.com/flutter/uxr/pull/100
  - In the [`flutter/uxr`](https://github.com/flutter/uxr) repo, restructuring the json to more flexible
- [x] https://github.com/dart-lang/tools/pull/134

These can be done after pilot:
- [x] https://github.com/flutter/uxr/pull/104

**Comment by eliasyishak** [comment]
@jayoung-lee just a heads up, this feature will never return any surveys for users that have decided to opt out of telemetry collection already

**Comment by jayoung-lee** [comment]
Thank you for the heads up @eliasyishak. That's exactly what I was looking for, and I really appreciate that the feature respects users' decisions to opt out of telemetry!

**Comment by eliasyishak** [comment]
With https://github.com/flutter/uxr/pull/104 getting merged today, the development of this feature is finished.
